/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spireofbabel_raknet4j_ReplicaManager3_ReplicaManager3 */

#ifndef _Included_com_spireofbabel_raknet4j_ReplicaManager3_ReplicaManager3
#define _Included_com_spireofbabel_raknet4j_ReplicaManager3_ReplicaManager3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spireofbabel_raknet4j_ReplicaManager3_ReplicaManager3
 * Method:    nativeReplicaManager3
 * Signature: ()Lcom/spireofbabel/raknet4j/NativeHandle;
 */
JNIEXPORT jobject JNICALL Java_com_spireofbabel_raknet4j_ReplicaManager3_ReplicaManager3_nativeReplicaManager3
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
