/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spireofbabel_raknet4j_ConsoleServer */

#ifndef _Included_com_spireofbabel_raknet4j_ConsoleServer
#define _Included_com_spireofbabel_raknet4j_ConsoleServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spireofbabel_raknet4j_ConsoleServer
 * Method:    nativeGetInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_spireofbabel_raknet4j_ConsoleServer_nativeGetInstance
  (JNIEnv *, jclass);

/*
 * Class:     com_spireofbabel_raknet4j_ConsoleServer
 * Method:    nativeDestroyInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_spireofbabel_raknet4j_ConsoleServer_nativeDestroyInstance
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
