/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spireofbabel_raknet4j_RakNetSocket2_RakNetSocket2 */

#ifndef _Included_com_spireofbabel_raknet4j_RakNetSocket2_RakNetSocket2
#define _Included_com_spireofbabel_raknet4j_RakNetSocket2_RakNetSocket2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spireofbabel_raknet4j_RakNetSocket2_RakNetSocket2
 * Method:    SetRecvEventHandler
 * Signature: (Lcom/spireofbabel/raknet4j/RakNetSocket2/RNS2EventHandler;)V
 */
JNIEXPORT void JNICALL Java_com_spireofbabel_raknet4j_RakNetSocket2_RakNetSocket2_SetRecvEventHandler
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_spireofbabel_raknet4j_RakNetSocket2_RakNetSocket2
 * Method:    Send
 * Signature: ([Lcom/spireofbabel/raknet4j/RakNetSocket2/SendParameters;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_spireofbabel_raknet4j_RakNetSocket2_RakNetSocket2_Send
  (JNIEnv *, jobject, jobjectArray, jstring, jint);

/*
 * Class:     com_spireofbabel_raknet4j_RakNetSocket2_RakNetSocket2
 * Method:    GetSocketType
 * Signature: ()Lcom/spireofbabel/raknet4j/RakNetSocket2/RakNetSocket2/RNS2Type;
 */
JNIEXPORT jobject JNICALL Java_com_spireofbabel_raknet4j_RakNetSocket2_RakNetSocket2_GetSocketType
  (JNIEnv *, jobject);

/*
 * Class:     com_spireofbabel_raknet4j_RakNetSocket2_RakNetSocket2
 * Method:    SetSocketType
 * Signature: (Lcom/spireofbabel/raknet4j/RakNetSocket2/RakNetSocket2/RNS2Type;)V
 */
JNIEXPORT void JNICALL Java_com_spireofbabel_raknet4j_RakNetSocket2_RakNetSocket2_SetSocketType
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_spireofbabel_raknet4j_RakNetSocket2_RakNetSocket2
 * Method:    IsBerkleySocket
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_spireofbabel_raknet4j_RakNetSocket2_RakNetSocket2_IsBerkleySocket
  (JNIEnv *, jobject);

/*
 * Class:     com_spireofbabel_raknet4j_RakNetSocket2_RakNetSocket2
 * Method:    GetBoundAddress
 * Signature: ()Lcom/spireofbabel/raknet4j/RakNetSocket2/SystemAddress;
 */
JNIEXPORT jobject JNICALL Java_com_spireofbabel_raknet4j_RakNetSocket2_RakNetSocket2_GetBoundAddress
  (JNIEnv *, jobject);

/*
 * Class:     com_spireofbabel_raknet4j_RakNetSocket2_RakNetSocket2
 * Method:    GetUserConnectionSocketIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_spireofbabel_raknet4j_RakNetSocket2_RakNetSocket2_GetUserConnectionSocketIndex
  (JNIEnv *, jobject);

/*
 * Class:     com_spireofbabel_raknet4j_RakNetSocket2_RakNetSocket2
 * Method:    SetUserConnectionSocketIndex
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_spireofbabel_raknet4j_RakNetSocket2_RakNetSocket2_SetUserConnectionSocketIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_spireofbabel_raknet4j_RakNetSocket2_RakNetSocket2
 * Method:    GetEventHandler
 * Signature: ()Lcom/spireofbabel/raknet4j/RakNetSocket2/RNS2EventHandler;
 */
JNIEXPORT jobject JNICALL Java_com_spireofbabel_raknet4j_RakNetSocket2_RakNetSocket2_GetEventHandler
  (JNIEnv *, jobject);

/*
 * Class:     com_spireofbabel_raknet4j_RakNetSocket2_RakNetSocket2
 * Method:    GetMyIP
 * Signature: ([Lcom/spireofbabel/raknet4j/RakNetSocket2/SystemAddress;)V
 */
JNIEXPORT void JNICALL Java_com_spireofbabel_raknet4j_RakNetSocket2_RakNetSocket2_GetMyIP
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     com_spireofbabel_raknet4j_RakNetSocket2_RakNetSocket2
 * Method:    DomainNameToIP
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_spireofbabel_raknet4j_RakNetSocket2_RakNetSocket2_DomainNameToIP
  (JNIEnv *, jclass, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
