/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spireofbabel_raknet4j_BitStream */

#ifndef _Included_com_spireofbabel_raknet4j_BitStream
#define _Included_com_spireofbabel_raknet4j_BitStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spireofbabel_raknet4j_BitStream
 * Method:    nativeGetInstance
 * Signature: ()Lcom/spireofbabel/raknet4j/NativeHandle;
 */
JNIEXPORT jobject JNICALL Java_com_spireofbabel_raknet4j_BitStream_nativeGetInstance
  (JNIEnv *, jclass);

/*
 * Class:     com_spireofbabel_raknet4j_BitStream
 * Method:    nativeDestroyInstance
 * Signature: (Lcom/spireofbabel/raknet4j/NativeHandle;)Lcom/spireofbabel/raknet4j/NativeHandle;
 */
JNIEXPORT jobject JNICALL Java_com_spireofbabel_raknet4j_BitStream_nativeDestroyInstance
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
