/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spireofbabel_raknet4j_ReplicaManager3_Replica3_RM3SerializationResult */

#ifndef _Included_com_spireofbabel_raknet4j_ReplicaManager3_Replica3_RM3SerializationResult
#define _Included_com_spireofbabel_raknet4j_ReplicaManager3_Replica3_RM3SerializationResult
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
