/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spireofbabel_raknet4j_RakNetGUID */

#ifndef _Included_com_spireofbabel_raknet4j_RakNetGUID
#define _Included_com_spireofbabel_raknet4j_RakNetGUID
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spireofbabel_raknet4j_RakNetGUID
 * Method:    nativeRakNetGUID
 * Signature: ()Lcom/spireofbabel/raknet4j/NativeHandle;
 */
JNIEXPORT jobject JNICALL Java_com_spireofbabel_raknet4j_RakNetGUID_nativeRakNetGUID__
  (JNIEnv *, jobject);

/*
 * Class:     com_spireofbabel_raknet4j_RakNetGUID
 * Method:    nativeRakNetGUID
 * Signature: (J)Lcom/spireofbabel/raknet4j/NativeHandle;
 */
JNIEXPORT jobject JNICALL Java_com_spireofbabel_raknet4j_RakNetGUID_nativeRakNetGUID__J
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
