/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spireofbabel_raknet4j_NativeHandle */

#ifndef _Included_com_spireofbabel_raknet4j_NativeHandle
#define _Included_com_spireofbabel_raknet4j_NativeHandle
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
