/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spireofbabel_raknet4j_PublicKey_PublicKeyMode */

#ifndef _Included_com_spireofbabel_raknet4j_PublicKey_PublicKeyMode
#define _Included_com_spireofbabel_raknet4j_PublicKey_PublicKeyMode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
