/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spireofbabel_raknet4j_RakNetSocket2_RakNetSocket2_RNS2Type */

#ifndef _Included_com_spireofbabel_raknet4j_RakNetSocket2_RakNetSocket2_RNS2Type
#define _Included_com_spireofbabel_raknet4j_RakNetSocket2_RakNetSocket2_RNS2Type
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
