/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spireofbabel_raknet4j_ReplicaManager3_Connection_RM3_ConstructionMode */

#ifndef _Included_com_spireofbabel_raknet4j_ReplicaManager3_Connection_RM3_ConstructionMode
#define _Included_com_spireofbabel_raknet4j_ReplicaManager3_Connection_RM3_ConstructionMode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
