/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spireofbabel_raknet4j_ReplicaManager3_DeserializeParameters */

#ifndef _Included_com_spireofbabel_raknet4j_ReplicaManager3_DeserializeParameters
#define _Included_com_spireofbabel_raknet4j_ReplicaManager3_DeserializeParameters
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spireofbabel_raknet4j_ReplicaManager3_DeserializeParameters
 * Method:    nativeDeserializeParameters
 * Signature: ()Lcom/spireofbabel/raknet4j/NativeHandle;
 */
JNIEXPORT jobject JNICALL Java_com_spireofbabel_raknet4j_ReplicaManager3_DeserializeParameters_nativeDeserializeParameters
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
