/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spireofbabel_raknet4j_RakNetSocket2_SystemAddress */

#ifndef _Included_com_spireofbabel_raknet4j_RakNetSocket2_SystemAddress
#define _Included_com_spireofbabel_raknet4j_RakNetSocket2_SystemAddress
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spireofbabel_raknet4j_RakNetSocket2_SystemAddress
 * Method:    nativeSystemAddress
 * Signature: ()Lcom/spireofbabel/raknet4j/NativeHandle;
 */
JNIEXPORT jobject JNICALL Java_com_spireofbabel_raknet4j_RakNetSocket2_SystemAddress_nativeSystemAddress__
  (JNIEnv *, jclass);

/*
 * Class:     com_spireofbabel_raknet4j_RakNetSocket2_SystemAddress
 * Method:    nativeSystemAddress
 * Signature: (Ljava/lang/String;)Lcom/spireofbabel/raknet4j/NativeHandle;
 */
JNIEXPORT jobject JNICALL Java_com_spireofbabel_raknet4j_RakNetSocket2_SystemAddress_nativeSystemAddress__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_spireofbabel_raknet4j_RakNetSocket2_SystemAddress
 * Method:    nativeSystemAddress
 * Signature: (Ljava/lang/String;I)Lcom/spireofbabel/raknet4j/NativeHandle;
 */
JNIEXPORT jobject JNICALL Java_com_spireofbabel_raknet4j_RakNetSocket2_SystemAddress_nativeSystemAddress__Ljava_lang_String_2I
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_spireofbabel_raknet4j_RakNetSocket2_SystemAddress
 * Method:    nativeDestroyInstance
 * Signature: (Lcom/spireofbabel/raknet4j/NativeHandle;)V
 */
JNIEXPORT void JNICALL Java_com_spireofbabel_raknet4j_RakNetSocket2_SystemAddress_nativeDestroyInstance
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
