/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spireofbabel_raknet4j_ReplicaManager3_Connection_RM3 */

#ifndef _Included_com_spireofbabel_raknet4j_ReplicaManager3_Connection_RM3
#define _Included_com_spireofbabel_raknet4j_ReplicaManager3_Connection_RM3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spireofbabel_raknet4j_ReplicaManager3_Connection_RM3
 * Method:    nativeConnection_RM3
 * Signature: ()Lcom/spireofbabel/raknet4j/NativeHandle;
 */
JNIEXPORT jobject JNICALL Java_com_spireofbabel_raknet4j_ReplicaManager3_Connection_1RM3_nativeConnection_1RM3__
  (JNIEnv *, jobject);

/*
 * Class:     com_spireofbabel_raknet4j_ReplicaManager3_Connection_RM3
 * Method:    nativeConnection_RM3
 * Signature: (Lcom/spireofbabel/raknet4j/RakNetSocket2/SystemAddress;Lcom/spireofbabel/raknet4j/RakNetGUID;)Lcom/spireofbabel/raknet4j/NativeHandle;
 */
JNIEXPORT jobject JNICALL Java_com_spireofbabel_raknet4j_ReplicaManager3_Connection_1RM3_nativeConnection_1RM3__Lcom_spireofbabel_raknet4j_RakNetSocket2_SystemAddress_2Lcom_spireofbabel_raknet4j_RakNetGUID_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_spireofbabel_raknet4j_ReplicaManager3_Connection_RM3
 * Method:    nativeDestroyInstance
 * Signature: (Lcom/spireofbabel/raknet4j/NativeHandle;)V
 */
JNIEXPORT void JNICALL Java_com_spireofbabel_raknet4j_ReplicaManager3_Connection_1RM3_nativeDestroyInstance
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_spireofbabel_raknet4j_ReplicaManager3_Connection_RM3
 * Method:    AllocReplica
 * Signature: (Lcom/spireofbabel/raknet4j/BitStream;Lcom/spireofbabel/raknet4j/ReplicaManager3/ReplicaManager3;)Lcom/spireofbabel/raknet4j/ReplicaManager3/Replica3;
 */
JNIEXPORT jobject JNICALL Java_com_spireofbabel_raknet4j_ReplicaManager3_Connection_1RM3_AllocReplica
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_spireofbabel_raknet4j_ReplicaManager3_Connection_RM3
 * Method:    GetConstructedReplicas
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_spireofbabel_raknet4j_ReplicaManager3_Connection_1RM3_GetConstructedReplicas
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_spireofbabel_raknet4j_ReplicaManager3_Connection_RM3
 * Method:    HasReplicaConstructed
 * Signature: (Lcom/spireofbabel/raknet4j/ReplicaManager3/Replica3;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_spireofbabel_raknet4j_ReplicaManager3_Connection_1RM3_HasReplicaConstructed
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_spireofbabel_raknet4j_ReplicaManager3_Connection_RM3
 * Method:    GetSystemAddress
 * Signature: ()Lcom/spireofbabel/raknet4j/RakNetSocket2/SystemAddress;
 */
JNIEXPORT jobject JNICALL Java_com_spireofbabel_raknet4j_ReplicaManager3_Connection_1RM3_GetSystemAddress
  (JNIEnv *, jobject);

/*
 * Class:     com_spireofbabel_raknet4j_ReplicaManager3_Connection_RM3
 * Method:    GetRakNetGUID
 * Signature: ()Lcom/spireofbabel/raknet4j/RakNetGUID;
 */
JNIEXPORT jobject JNICALL Java_com_spireofbabel_raknet4j_ReplicaManager3_Connection_1RM3_GetRakNetGUID
  (JNIEnv *, jobject);

/*
 * Class:     com_spireofbabel_raknet4j_ReplicaManager3_Connection_RM3
 * Method:    GetDownloadWasCompleted
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_spireofbabel_raknet4j_ReplicaManager3_Connection_1RM3_GetDownloadWasCompleted
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
