/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spireofbabel_raknet4j_RakNetEnums_ConnectionAttemptResult */

#ifndef _Included_com_spireofbabel_raknet4j_RakNetEnums_ConnectionAttemptResult
#define _Included_com_spireofbabel_raknet4j_RakNetEnums_ConnectionAttemptResult
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
